// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdrsbwgmzsbodheixmix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcnNid2dtenNib2RoZWl4bWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjQ0NjcsImV4cCI6MjA1NjI0MDQ2N30.WeST1cjw-f4tg86ar9JvCLBAhXxsDcIL5aO0cpCm9AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);